[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd client && npm run dev"
  port = 5173
  publish = "client/dist"
