services:
  - type: web
    name: fge-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: dpg-cp8l4q8l6cac73b4u4e0-a.singapore-postgres.render.com
      - key: DB_USER
        value: fge_db_user
      - key: DB_PASSWORD
        value: W4fLk4aXx2X1dGxE1eUQN6i4NnBmYVc2
      - key: DB_NAME
        value: fge_db_yh9s
      - key: JWT_SECRET
        value: a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2
      - key: JWT_EXPIRE
        value: 30d
      - key: FRONTEND_URL
        value: https://fgetestplatform.netlify.app
      - key: PGSSLMODE
        value: require
    plan: free
    numInstances: 1
    healthCheckPath: /api/health
    autoDeploy: true

# Database configuration
databases:
  - name: fge_db
    databaseName: fge_db_yh9s
    user: fge_db_user
    plan: free
